### ISSUE TITLE
Consider using SQLIte in memory database for test, or exclude generated SQLite used in test

### ISSUE THREAD

**Issue by mosbth** [lrc-se/bth-anax-repository#2]
I see that two files are modified when running the tests. Consider to exclude them from the repo to avoid repo changes just related to running a test. Or use in-memory database as an alternative for tests.
``` 
      modified:   test/db/test.sqlite 
      modified:   test/db/test2.sqlite
```

**Comment by lrc-se** [comment]
I opted for excluding the database files from the repo, utilizing setup scripts to define the schema upon file creation.

[commit](https://github.com/lrc-se/bth-anax-repository/commit/153e852a35bccdab698d2a0420243a4a5ffcf7ec)
